---
env:
  - PLATFORM=debian-jessie

sudo: required

language: python

services:
  - docker

before_install:
    - docker info
    - docker version

script:
  - docker build -f tests/$PLATFORM.Dockerfile -t test-$PLATFORM . && docker run --name $PLATFORM test-$PLATFORM

after_failure:
  - ansible --version
  - ansible -i 127.0.0.1, -m setup all -c local

notifications:
  slack: ambimax:2MlPTX9bY9aPxCPhJGxHKIT6
  webhooks: https://galaxy.ansible.com/api/v1/notifications/